Refactor/connect auth with backend
tactful-ai/Dstny-Integrator-Hub pull request #18
Opened 2023-09-12 13:09 UTC by ahmedasad236

2023-09-12 21:04 UTC, a-asmaa requested changes
@ahmedasad236 please remove apps that are created for test

2023-09-12 21:25 UTC, ahmedasad236 commented
Done @a-asmaa

2023-09-13 09:18 UTC, a-asmaa requested changes
there're some comments that need to be checked through different components "generic", 
like:
- Delete wrapping box and tag number and use their style.
- sending form data as params in URL
- Move backend integration "fetch" into a separate file
- ....
and please change create integration in sidebar => to integration and should route to the integration list page

2023-09-14 09:33 UTC, ahmedasad236 commented on packages/web/src/components/AuthNewForm/index.tsx
> +                        />
**YES**

2023-09-14 09:34 UTC, ahmedasad236 commented on packages/web/src/components/AuthSecondStep/index.tsx
> +            <AuthTestRequesForm control={control} register={register} />
** I tried to do that, but I think it looks good. as the form content will make this component much bigger**

2023-09-14 10:25 UTC, a-asmaa approved these changes

2023-09-14 11:17 UTC, merged